### PR TITLE
Added numpy() method

### PR DESCRIPTION
**Pull request by alexander-g**
`kp.Tensor.data()` returns a list of floats which is neither convenient nor efficient for further processing. I have added the `.numpy()` method which directly returns a numpy array.

### CODE REVIEW

**Comment by axsaucedo** [comment]
Very cool @alexander-g, good addition! Would you be able to add a test in the python test in the `test` folder? Mainly to make sure it works as expected before doing the releases. You will have to add `numpy` to the `reuirements-dev.txt`. If you get a chance to add further docuentation that is a plus, but it gets much more fiddly on how to build the docs so we can do that separate to this PR

**Comment by axsaucedo** [comment]
Fixes #104

**Comment by alexander-g** [comment]
Added tests.
Docs have to wait until I have figured out how to build them

**Comment by axsaucedo** [comment]
Looks good @alexander-g, thanks for the contribution

**Pull request merged**
