### PR TITLE
Added further tests to CI and provide Dockerimage with builds to swiftshader

### PR DESCRIPTION
**Pull request by axsaucedo**
Extended work on #114 

PR includes:
* Docker image for building Kompute related work with all dependencies
* Further test coverage in github action for C++ tests
* Coverage for (some initial) Pyhton tests via separate action
* Added Numpy as Setup.py dependency (potentially should explore making it optional)
* Added Python dependencies to run tests

Outstanding (to cover in PR or open respective issues):
* [x] Documentation
* [x] Running further Python tests
* [x] Running further C++ tests
* [x] Make Numpy dependency optional - For now we'll keep it as required dependency

### CODE REVIEW

**Comment by alexander-g** [comment]
Consider adding `pyshaderc` to `requirements-dev.txt` and compiling GLSL in the tests:
`spirv = pyshaderc.compile_into_spirv(glsl_bytes, 'comp', filepath='')`

**Comment by axsaucedo** [comment]
Interesting @alexander-g, good idea, that could provide full coverage of the tests, let me give it a shot

**Comment by alexander-g** [comment]
> Make Numpy dependency optional

What's the reasoning behind this? Numpy is de-facto standard in anything computing related.

**Comment by axsaucedo** [comment]
@alexander-g the module was failing to import if the numpy dependency was not present, so I added it to setup.py - it's mainly to assess whether there would be users who would like to install Kompute without numpy to minimise dependencies. I do agree that numpy is the defacto standard in python so should make sense to have it by default.

**Comment by axsaucedo** [comment]
Just looking at PyShaderc it doesn't look like it's currently maintained (no updates since 2017), so not sure adding it as a dependency. I am continuously surprised the lack of tools / utilities around GPGPU workflows, particularly around Python - let me give it some thought, as I would rather take in something along the lines of a simple GLSL utility function that is limited but maintained than bringing in packages that don't have too much support. Thinking outloud on this, I had a few interactions with the author of https://github.com/pygfx/pyshader - it may actually be a good opportunity for them to adopt some of these functionalities.

**Comment by alexander-g** [comment]
Yes it's not maintained any more but it's supposed to be only a dependency for tests, not for the end user.

**Comment by axsaucedo** [comment]
That's technically correct, but currently large number of users would use the tests for guidance on how to use the library (that's largely how pybind11 provides insights to more advanced usage, by pointing users to the unit tests) - having said that, I think if there is a way to explore a more active project like pyshader to offer these functionalities. Let me reach out to the pyshader project, as that would be the ideal, but if that's not an option I think pyshaderc is still a good choice to get further coverage of tests.

**Comment by axsaucedo** [comment]
Updated docs https://kompute.cc/overview/ci-tests.html

**Comment by axsaucedo** [comment]
Added #121 to ensure the rest of the tests are covered

**Pull request merged**
